language: java
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
  - $HOME/.m2
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - rm ~/.m2/settings.xml
install: mvn install -DskipTests=true -Dgpg.skip=true -Dmaven.javadoc.skip=true -B -V -U
after_success:
  - mvn clean test jacoco:report coveralls:report
